# Describes the format for available Flo services

set_sleep_mode:
  target:
    entity:
      integration: flo
      domain: switch
  fields:
    sleep_minutes:
      required: true
      selector:
        select:
          options:
            - "120"
            - "1440"
            - "4320"
    revert_to_mode:
      required: true
      selector:
        select:
          options:
            - "away"
            - "home"
set_away_mode:
  target:
    entity:
      integration: flo
      domain: switch
set_home_mode:
  target:
    entity:
      integration: flo
      domain: switch
run_health_test:
  target:
    entity:
      integration: flo
      domain: switch
